# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CoxHessianHelper <- function(x, multiplier, eta, order_b1, rankmin_b1) {
    .Call('_snpnet_CoxHessianHelper', PACKAGE = 'snpnet', x, multiplier, eta, order_b1, rankmin_b1)
}

#' @export
eigenCrossProd <- function(A) {
    .Call('_snpnet_eigenCrossProd', PACKAGE = 'snpnet', A)
}

